/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
          "tertiary-fixed-dim": "#e9c349",
          "on-secondary-container": "#754000",
          "inverse-surface": "#31312a",
          "on-primary-fixed-variant": "#871f25",
          "inverse-on-surface": "#f4f0e7",
          "surface-container-lowest": "#ffffff",
          "on-background": "#1c1c16",
          "secondary-container": "#feac61",
          "on-secondary-fixed-variant": "#6c3a00",
          "tertiary-container": "#cca730",
          "primary-container": "#7c161e",
          "primary-fixed": "#ffdad8",
          "surface-container-high": "#ece8de",
          "on-surface": "#1c1c16",
          "outline": "#8b7170",
          "outline-variant": "#debfbe",
          "on-primary-fixed": "#410006",
          "surface-variant": "#e6e2d8",
          "background": "#fdf9ef",
          "on-error-container": "#93000a",
          "surface-dim": "#dddad0",
          "surface-bright": "#fdf9ef",
          "secondary-fixed-dim": "#ffb778",
          "tertiary-fixed": "#ffe088",
          "surface-container-highest": "#e6e2d8",
          "surface-container": "#f1eee4",
          "tertiary": "#735c00",
          "error": "#ba1a1a",
          "on-surface-variant": "#574140",
          "surface-container-low": "#f7f3e9",
          "inverse-primary": "#ffb3b0",
          "on-primary": "#ffffff",
          "primary": "#5a000c",
          "secondary": "#8d4f06",
          "surface-tint": "#a7373a",
          "secondary-fixed": "#ffdcc1",
          "on-tertiary-fixed": "#241a00",
          "on-tertiary": "#ffffff",
          "on-secondary-fixed": "#2e1500",
          "on-secondary": "#ffffff",
          "error-container": "#ffdad6",
          "on-error": "#ffffff",
          "primary-fixed-dim": "#ffb3b0",
          "on-tertiary-fixed-variant": "#574500",
          "on-tertiary-container": "#4e3d00",
          "on-primary-container": "#ff8785",
          "surface": "#fdf9ef"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "spacing": {
          "gutter": "24px",
          "margin-desktop": "80px",
          "unit": "8px",
          "margin-mobile": "16px",
          "container-padding": "40px"
      },
      "fontFamily": {
          "headline-xl": ["Bodoni Moda"],
          "body-md": ["Hanken Grotesk"],
          "body-lg": ["Hanken Grotesk"],
          "headline-lg": ["Bodoni Moda"],
          "label-caps": ["Hanken Grotesk"],
          "headline-lg-mobile": ["Bodoni Moda"],
          "headline-md": ["Bodoni Moda"],
          "label-sm": ["Hanken Grotesk"],
          // Keeping old fonts for fallback/components not yet migrated
          "display": ["Bodoni Moda", "serif"],
          "sans": ["Hanken Grotesk", "sans-serif"]
      },
      "fontSize": {
          "headline-xl": ["64px", { "lineHeight": "72px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
          "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
          "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
          "headline-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
          "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.15em", "fontWeight": "600" }],
          "headline-lg-mobile": ["32px", { "lineHeight": "40px", "fontWeight": "600" }],
          "headline-md": ["32px", { "lineHeight": "40px", "fontWeight": "500" }],
          "label-sm": ["14px", { "lineHeight": "20px", "fontWeight": "500" }]
      }
    },
  },
  plugins: [require("tailwindcss-animate")],
}
